Repository Ayu-hack/Restaurant-Management-System, pull requests merged in 2024-10, with the labels that each got.

#11 Dockerizing the application
  .gitignore
  Backend/.dockerignore
  Backend/Dockerfile
  Backend/db.js
  Backend/index.js
  Backend/services.js
  Frontend/Dockerfile
  Frontend/src/main.jsx
  Frontend/vite.config.js
  SQL Database/Bill.sql
  SQL Database/Dockerfile
  SQL Database/init.sql
  docker-compose.yml
  package-lock.json
Labels: Hacktoberfest

#13 Added solution for Dynamic Menu
  Backend/app.py
  SQL Database/Menu.sql
Labels: Hacktoberfest, Amazing Work

#15 Add Navbar and Button
  Frontend/src/app.jsx
  Frontend/src/imports.js
  Frontend/src/views/components/Navbar.jsx
  Frontend/src/views/pages/Home.jsx
Labels: good first issue, hacktoberfest-accepted

#18 Feature/enhancement
  Frontend/src/imports.js
  Frontend/src/views/components/LoadingSpinner.jsx
  Frontend/src/views/components/Navbar.jsx
  Frontend/src/views/components/Skelleton.jsx
  Frontend/src/views/pages/Orders.jsx
Labels: good first issue, hacktoberfest-accepted

#19 Add dark mode
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app.jsx
  Frontend/src/context/DarkModeContext.jsx
  Frontend/src/index.css
  Frontend/src/views/components/Cart.jsx
  Frontend/src/views/components/Itemframes.jsx
  Frontend/src/views/components/Navbar.jsx
  Frontend/src/views/pages/Home.jsx
  Frontend/src/views/pages/Orders.jsx
Labels: good first issue, hacktoberfest-accepted

#21 add favorite item
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app.jsx
  Frontend/src/context/FavoriteContext.jsx
  Frontend/src/imports.js
  Frontend/src/views/components/FavoriteItems.jsx
  Frontend/src/views/components/Itemframes.jsx
  Frontend/src/views/components/Navbar.jsx
Labels: good first issue, hacktoberfest-accepted
